project_name: rustdesk-api-server
builds:
  - env: [ CGO_ENABLED=1 ]
    flags:
      - -v
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - '386'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm64'
checksum:
  name_template: 'checksums.txt'
archives:
  - format: tar.gz
    name_template: 'sctgdesk_api_server_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - img.png
      - conf/app.conf
nfpms:
  - vendor: "SCTG Development"
    homepage: "https://sctg.eu.org"
    maintainer: "Ronan <ronan@sctg.eu.org>"
    description: "sctgdesk-api-server"
    license: "Apache-2.0"

brews:
  - homepage: "https://sctg.eu.org"
    description: "sctgdesk-api-server"
    license: "Apache-2.0"
